services:
  jenkins:
    image: jenkins/jenkins:2.488
    ports:
      - "8081:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    network_mode: bridge
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PORT: "8080"
  ssh-agent:
    image: jenkins/ssh-agent:6.4.0
    network_mode: bridge

volumes:
  jenkins_data: