version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:2.24.0
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: "portainer.local.andrecfaria.com"
      VIRTUAL_PORT: "9000"
    network_mode: bridge

volumes:
  portainer_data: