services:
  portainer:
    image: portainer/portainer-ce:${VERSION}
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - "./certs:/certs"
    command:
      --sslcert /certs/portainer.crt
      --sslkey /certs/portainer.key
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PROTO: "https"
      VIRTUAL_PORT: "9443"
    network_mode: bridge

volumes:
  portainer_data:
