services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.4
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./certs:/etc/nginx/certs"
    network_mode: bridge