services:
  nginx-proxy:
    image: docker.io/jc21/nginx-proxy-manager:2.12.3
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "8181:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_certs:/etc/letsencrypt
    network_mode: bridge

volumes:
  npm_data:
  npm_certs: