services:
  convertx:
      image: "c4illin/convertx:main"
      ports:
        - 3000:3000
      volumes:
        - type: bind
          source: ${DATA_DIR}
          target: /app/data
      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
