services:
  convertx:
      image: "c4illin/convertx:${CONVERTX_VERSION}"
      ports:
        - 3000:3000
      volumes:
        - type: bind
          source: ${DOCKER_SWARM_STORAGE}/convertx/data
          target: /app/data
      environment:
        - JWT_SECRET=${CONVERTX_JWT} # will use randomUUID() if unset
      # - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection
      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
