services:
  mealie:
      image: hkotel/mealie:v3.22.0
      ports:
        - 9292:9000
      volumes:
        - type: bind
          source: ${DATA_DIR}
          target: /app/data
      environment:
        ALLOW_SIGNUP: "false"
        LOG_LEVEL: error
        DB_ENGINE: sqlite
      healthcheck:
        test: ["CMD", "/app/healthcheck.sh"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s
      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
