services:
  nginx-reverse-proxy:
      image: "docker.io/jc21/nginx-proxy-manager:2.15.1"
      ports:
        - 80:80
        - 8181:81
        - 443:443
      volumes:
        - type: bind
          source: ${DATA_DIR}
          target: /data
        
        - type: bind
          source: ${CERTS_DIR}
          target: /etc/letsencrypt
      healthcheck:
        test: ["CMD", "/usr/bin/check-health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
