services:
  uptime-kuma:
      user: 1000:1000
      image: louislam/uptime-kuma:2.5.0
      ports:
        - 3001:3001
      volumes:
        - type: bind
          source: ${DATA_DIR}
          target: /app/data
        - type: bind
          source: ${HOMELAB_CA_CERTS}
          target: /etc/ssl/certs/vault-ca-bundle.pem
          read_only: true
      environment:
        - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/vault-ca-bundle.pem
      healthcheck:
        test: ["CMD", "/app/extra/healthcheck"]
        interval: 60s
        timeout: 30s
        retries: 5
        start_period: 180s
      networks:
        - network
        - proxy
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
  proxy:
    name: homelab-proxy
    external: true
