services:
  vault:
      image: "hashicorp/vault:2.0.1"
      ports:
        - 8200:8200
      entrypoint: vault server -config /vault/config/config.hcl
      cap_add:
        - IPC_LOCK
      volumes:
        - type: bind
          source: ${DATA_DIR}
          target: /vault/data

        - type: bind
          source: ${LOG_DIR}
          target: /vault/logs

        - type: bind
          source: ${CERTS_DIR}
          target: /certs
        
        - type: bind
          source: ${VAULT_CONFIG_HCL}
          target: /vault/config/config.hcl

      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

networks:
  network:
    driver: overlay
    attachable: true
