version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma_data:/app/data
    environment:
      VIRTUAL_HOST: "monitoring.local.andrecfaria.com"
      VIRTUAL_PORT: "3001"
    network_mode: bridge

volumes:
  uptimekuma_data: