version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma_data:/app/data
      - "./certs:/app/certs"
    environment:
      VIRTUAL_HOST: "monitoring.local.andrecfaria.com"
      VIRTUAL_PORT: "3001"
      VIRTUAL_PROTO: "https"
      NODE_EXTRA_CA_CERTS: "/app/certs/ca-chain.pem"
      UPTIME_KUMA_SSL_CERT: "/app/certs/uptimekuma.crt"
      UPTIME_KUMA_SSL_KEY: "/app/certs/uptimekuma.key"
    network_mode: bridge

volumes:
  uptimekuma_data: