---
- name: Deploy Semaphore UI
  hosts: docker_mgr_nodes
  become: true

  tasks:
    - name: Create directory for compose file
      ansible.builtin.file:
        path: /etc/docker/
        state: directory
        mode: '0755'

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ../docker/semaphore-stack.yml
        dest: /etc/docker/semaphore-stack.yml
        mode: '0755'

    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: semaphore
        compose:
          - /etc/docker/semaphore-stack.yml