---
- name: Install and configure Vault Agent
  hosts: all
  become: true

  tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:

    - name: Determine OS architecture
      set_fact:
        architecture: "{{ ansible_facts['architecture'] }}"

    # - name: Create directory for Vault binary
    #   ansible.builtin.file:
    #     path: /etc/vault/
    #     state: directory
    #     mode: '0755'

    - name: Download Vault archive (ARM64)
      ansible.builtin.unarchive:
        src: 'https://releases.hashicorp.com/vault/1.18.0/vault_1.18.0_linux_arm64.zip'
        dest: /bin/
        remote_src: yes
      when: architecture == "aarch64"

    - name: Download Vault archive (AMD64)
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/vault/1.18.0/vault_1.18.0_linux_amd64.zip
        dest: /bin/
        remote_src: yes
      when: architecture == "amd64"

    